### ISSUE TITLE
"Make it Sound Worse" ? Colab inference script really bad audio quality

### ISSUE THREAD

**Issue by jarredou** [interactiveaudiolab/MSG#20]
Is it normal that the audio output quality is so degraded with the colab inference script ?
Stereo sources are degraded into mono while demucs/spleeter extracted stems are always stereo and sample rate is downgraded to 16kHz. So much information is lost during the process ! 

I thought it would "Make it Sound Good", but it "Make it Sound Worse". Really worse...  The opposite of  "_a post-processor that enhances the output quality of source separation_ " !

**Comment by noahschaffer** [comment]
Hi, sorry to hear the Colab wasn’t working for you. It’s possible there is an issue with the checkpoints so we will take a look at that. 

I’d be happy to further communicate regarding the areas in which our model does/doesn’t work and how we can fix issues with the colab script. Please look in the paper to the listener studies for what we are using to make our claims of enhancing quality of audio output, as well as where our model falls short.

**Comment by noahschaffer** [comment]
Just checked the Colab script and it seems to be working on my end.

Re monophonic audio and sample rate: the goal of this project was to create a post-processor which removes noise and recovers transients from separation output. We downsample and use mono so we can accommodate multiple separators. We have left the task of bandwidth extension and stereophonic enhancement to future work (see paper). Please reach out to me individually if you have any further questions 
Noahschaffer2022@u.northwestern.edu
